;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-item
        ac-pcmp/self-insert-command-with-ac-start
        artist-down-mouse-1
        delete-window
        helm-mini
        keyboard-escape-quit
        mark-whole-buffer
        mouse-set-region
        org-force-self-insert
        org-return-indent
        org-self-insert-command
        org-yank
        toggle-frame-fullscreen
        TeX-insert-backslash
        ))

(setq mc/cmds-to-run-once
      '(
        TeX-insert-backslash
        TeX-next-error
        TeX-recenter-output-buffer
        artist-previous-line
        electric-newline-and-maybe-indent
        exit-recursive-edit
        kill-this-buffer
        org-ctrl-c-ctrl-c
        org-export-dispatch
        org-forward-paragraph
        org-insert-heading
        org-metadown
        org-metaup
        org-shiftcontroldown
        org-shiftdown
        set-goal-column
        ))
