* Grafo
#+BEGIN_SRC dot :file ./dunnet.svg :exports results :cmd dot :cmdline -Tsvg
digraph{

  edge[arrowhead="none"]

  "shovel" -> "Dead end" [style="dotted"]
  "Dead end" -> "E/W Dirt road"
  "boulder" -> "E/W Dirt road"
  "E/W Dirt road" -> "Fork"
  "cpu" -> "Fork" [style="dotted"]
  "Fork" -> "SE/NW road"
  "food" -> "SE/NW road" [style="dotted"]
  "SE/NW road" -> "Bear hangout"
  "key" -> "Bear hangout" [style="dotted"]
  "Bear hangout" -> "Hidden area"
  "bracelet" -> "Hidden area" [style="dotted"]
  "Fork" -> "NE/SW road"
  "NE/SW road" -> "Building front"
  "Building front" -> "Old Building hallway"
  "Old Building hallway" -> "Computer room"
  "paper" -> "Computer room" [style="dotted"]
  "Computer room" -> "Pockey"
  "Pockey" -> "Receiving room"
  "Receiving room" -> "Northbound Hallway"
  "Northbound Hallway" -> "Sauna"
  "Northbound Hallway" -> "End of N/S Hallway"
  "End of N/S Hallway" -> "Weight room"
  "Weight room" -> "Maze button room"
  "button" -> "Maze button room" [style="dotted"]
  "Maze button room" -> "Maze"
  "statuette" -> "Maze" [style="dotted"]
  "floppy" -> "Maze" [style="dotted"]
  "Maze" -> "Reception area"
  "Reception area" -> "Health Club front"
  "Health Club front" -> "Lakefront North"
  "Lakefront North" -> "Lakefront South"
  "Lakefront South" -> "Cave Entrance" [taillabel="s"]
  "chute" -> "Cave Entrance" [style="dotted"]
  "Cave Entrance" -> "Misty Room" [taillabel="s"]
  "gold bar" -> "Misty Room" [style="dotted"] 
  "Misty Room" -> "Cave E/W passage" [taillabel="e"]
  "Cave E/W passage" -> "N/S/W Junction" [taillabel="e"]
  "N/S/W Junction" -> "North end of cave passage" [taillabel="n"]
  "North end of cave passage" -> "Bedroom" [taillabel="d"]
  "painting" -> "Bedroom" [style="dotted"]
  "Bedroom" -> "NE end of NE/SW cave passage" [taillabel="d"]
  "NE end of NE/SW cave passage" -> "NE/SW-E/W junction" [taillabel="sw"]
  "NE/SW-E/W junction" -> "East end of E/W cave passage" [taillabel="e"]
  "East end of E/W cave passage" -> "Horseshoe boulder room" [taillabel="u"]
  "NE/SW-E/W junction" -> "West end of E/W cave passage" [taillabel="w"]
  "West end of E/W cave passage" -> "Empty room" [taillabel="d"]
  "Empty room" -> "Blue room" [taillabel="n"]
  "Empty room" -> "Red room" [taillabel="e"]
  "Blue room" -> "Yellow room" [taillabel="e"]
  "Yellow room" -> "Red room" [taillabel="s"]
  "towel" -> "Red room" [style="dotted"]
  "Red room" -> "Long n/s hallway" [taillabel="d"]
  "Long n/s hallway" -> "3/4 north" [taillabel="n"]
  "3/4 north" -> "North end of long hallway" [taillabel="n"]
  "North end of long hallway" -> "Stair landing" [taillabel="u"]
  "box" -> "Stair landing" [style="dotted"]
  "Stair landing" -> "Top of staircase" [taillabel="u"]
  "Top of staircase" -> "NE crawlway" [taillabel="ne"]
  "NE crawlway" -> "Small crawlspace" [taillabel="ne"]
  "axe" -> "Small crawlspace" [style="dotted"]
  "Small crawlspace" -> "N/S/W Junction" [taillabel="d"]


  



  
}

#+END_SRC

#+RESULTS:
[[file:./dunnet.svg]]


* Prueba
#+begin_src bash :results drawer

set -x


log(){
  echo $* >> dunnet.log
}

clean_up(){
  log Finalizando script
  rm dunnet.in
  kill $(jobs -p)
}

set_up_fifo(){
  rm dunnet.in
  mkfifo dunnet.in
  sleep 30s > dunnet.in & #keep fifo open
}

set_up(){
  rm dunnet.log
  log "Comienza script"
  trap clean_up EXIT
}

run_dunnet(){
  local emacs=emacs-26.1
  $emacs -q --batch -l dunnet < dunnet.in | tee dunnet.tee.log &
  sleep 2
}


linea_a_linea(){
  log "Entro en línea a línea"
  while IFS='' read -r line || [[ -n "$line" ]]
  do
     log "Text read from file: $line"
     echo TECLEO: $line 
     echo $line > dunnet.in
     #sleep 0.0001
     echo ""
  done 
}

set_up

set_up_fifo

run_dunnet


linea_a_linea <<ENDOFGAME
take shovel
east
east
dig
look
take cpu
southeast
take food
southeast
drop food
look
take key
northwest
northwest
look
northeast
look
northeast
in
east
look bin
west
west
insert cpu into vax
type
toukmond
robert
ls
cd ..
ls
cd ..
ls
cd rooms
ls
cd hidden-area
ls
cat description
exit
e
s
look
sw
sw
se
se
sw
take bracelet
ne
nw
nw
ne
ne
in
w
look
type
cd /usr/toukmond
ls
uncompress paper.o.Z
exit
inventory
look paper
type
ftp gamma
anonymous
toukmond@pockey
help
type binary
send bracelet.o
send paper.o
send shovel.o
send key.o
send lamp.o
quit
ls
rlogin gamma
worms
take bracelet
take paper
take shovel
take key
take lamp
look bracelet
look lamp
look shovel
look key
east
east
look dial
turn dial counterclockwise
look
turn dial counterclockwise
look
turn dial counterclockwise
look
west
north
east
take weight
take life preserver
look life preserver
down
look button
press button

drop life preserver
drop bracelet
drop paper
drop shovel
drop key
up
take weight
down
put weight on button

nw
up
take floppy
take statuette
look statuette
# TENGO QUE VOLVER A LA SAUNA A FUNDIR LA STATUETTE
s
# ESTOY EN Maze little twisty passages
look
up
look
# ESTOY EN Maze thirsty little passages, al south little twisty, al se twenty little
se
look
# estoy en twenty little
down
look
# estoy en daze of twisty little, twisty little cabbages al nw
nw
look
# estoy en twisty little cabbages, reception area al nw
ne
# vuelvo a Weight room
w
s
drop floppy
e
# estoy en la sauna, a fundir la estatua
drop statuette
turn dial clockwise
turn dial clockwise
turn dial clockwise
take diamond
turn dial counterclockwise
turn dial counterclockwise
turn dial counterclockwise
turn dial counterclockwise
w
take floppy
look
quit
ENDOFGAME
exit


# DESPUES DE ABRIR EL maze PILLO EL INVENTARIO
take life preserver
take bracelet
take paper
take shovel
take key



se
down
nw
nw
s
s
s
s
put bracelet on chute
s
take gold bar
e
e
n
down
look painting
down
sw
e
up
look boulder


d
w
look
w
look
d
#empty room
n
e
s
n
e
s
look towel
take towel
down
n
n
u
look box
put key on box
look

# stair landing, box has exploded
u
u
ne
ne
get axe
look axe
d

#N/S/W Junction
n
look
d
sleep
# HAY QUE IR A LA HERRADURA Y ENTERRAR ALGO
d
sw
e
u
look
dig
look
take platinum bar
look platinum bar
quit

ENDOFGAME


clean_up

exit


#+END_SRC

#+RESULTS:
:RESULTS:

Dead end
You are at a dead end of a dirt road.  The road goes to the east.
In the distance you can see that it will eventually fork off.  The
trees here are very tall royal palms, and they are spaced equidistant
from each other.
There is a shovel here.
>TECLEO: take shovel

Taken.  
>TECLEO: east

E/W Dirt road
You are on the continuation of a dirt road.  There are more trees on
both sides of you.  The road continues to the east and west.
There is a large boulder here.
>TECLEO: east

Fork
You are at a fork of two passages, one to the northeast, and one to the
southeast.  The ground here seems very soft. You can also go back west.
>TECLEO: dig

I think you found something.
>TECLEO: look

Fork
You are at a fork of two passages, one to the northeast, and one to the
southeast.  The ground here seems very soft. You can also go back west.
There is a CPU card here.
>TECLEO: take cpu

Taken.  
>TECLEO: southeast

SE/NW road
You are on a southeast/northwest road.
There is some food here.
>TECLEO: take food

Taken.  
>TECLEO: southeast

Bear hangout
You are standing at the end of a road.  A passage leads back to the
northwest.
There is a ferocious bear here!
>TECLEO: drop food

Done.
The bear takes the food and runs away with it. He left something behind.
>TECLEO: look

Bear hangout
You are standing at the end of a road.  A passage leads back to the
northwest.
There is a shiny brass key here.
>TECLEO: take key

Taken.  
>TECLEO: northwest

SE/NW road
>TECLEO: northwest

Fork
>TECLEO: look

Fork
You are at a fork of two passages, one to the northeast, and one to the
southeast.  The ground here seems very soft. You can also go back west.
>TECLEO: northeast

NE/SW road
You are on a northeast/southwest road.
>TECLEO: look

NE/SW road
You are on a northeast/southwest road.
>TECLEO: northeast

Building front
You are at the end of the road.  There is a building in front of you
to the northeast, and the road leads back to the southwest.
>TECLEO: in

Old Building hallway
You are in the hallway of an old building.  There are rooms to the east
and west, and doors leading out to the north and south.
>TECLEO: east

Mailroom
You are in a mailroom.  There are many bins where the mail is usually
kept.  The exit is to the west.
>TECLEO: look bin

All of the bins are empty.  Looking closely you can see that there
are names written at the bottom of each bin, but most of them are
faded away so that you cannot read them.  You can only make out three
names:
                   Jeffrey Collier
                   Robert Toukmond
                   Thomas Stock

>TECLEO: west

Old Building hallway
>TECLEO: west

Computer room
You are in a computer room.  It seems like most of the equipment has
been removed.  There is a VAX 11/780 in front of you, however, with
one of the cabinets wide open.  A sign on the front of the machine
says: This VAX is named ‘pokey’.  To type on the console, use the
‘type’ command.  The exit is to the east.
The panel lights are steady and motionless.
>TECLEO: insert cpu into vax

As you put the CPU board in the computer, it immediately springs to life.
The lights start flashing, and the fans seem to startup.
>TECLEO: type



UNIX System V, Release 2.2 (pokey)

login: TECLEO: toukmond
password: 
TECLEO: robert

Welcome to Unix

Please clean up your directories.  The filesystem is getting full.
Our tcp/ip link to gamma is a little flaky, but seems to work.
The current version of ftp can only send files from your home
directory, and deletes them after they are sent!  Be careful.

Note: Restricted bourne shell in use.

$ 
TECLEO: ls

total 467
drwxr-xr-x  3 toukmond restricted      512 Jan 1 1970 .
drwxr-xr-x  3 root     staff          2048 Jan 1 1970 ..
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 ls
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 ftp
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 echo
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 exit
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 cd
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 pwd
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 rlogin
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 ssh
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 uncompress
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 cat
-rwxr-xr-x  1 toukmond restricted        0 Jan 1 1970 paper.o.Z
-rwxr-xr-x  1 toukmond restricted        0 Jan 1 1970 lamp.o
-rwxr-xr-x  1 toukmond restricted        0 Jan 1 1970 shovel.o
-rwxr-xr-x  1 toukmond restricted        0 Jan 1 1970 key.o
$ TECLEO: cd ..

$ TECLEO: ls

total 4
drwxr-xr-x  3 root     staff           512 Jan 1 1970 .
drwxr-xr-x  3 root     staff          2048 Jan 1 1970 ..
drwxr-xr-x  3 toukmond restricted      512 Jan 1 1970 toukmond
$ TECLEO: cd ..

$ TECLEO: ls

total 4
drwxr-xr-x  3 root     staff           512 Jan 1 1970 .
drwxr-xr-x  3 root     staff          2048 Jan 1 1970 ..
drwxr-xr-x  3 root     staff          2048 Jan 1 1970 usr
drwxr-xr-x  3 root     staff          2048 Jan 1 1970 rooms
$ TECLEO: cd rooms

$ TECLEO: ls

total 16
drwxr-xr-x  3 root     staff           512 Jan 1 1970 .
drwxr-xr-x  3 root     staff          2048 Jan 1 1970 ..
drwxr-xr-x  3 root     staff           512 Jan 1 1970 computer-room
drwxr-xr-x  3 root     staff           512 Jan 1 1970 mailroom
drwxr-xr-x  3 root     staff           512 Jan 1 1970 old-building-hallway
drwxr-xr-x  3 root     staff           512 Jan 1 1970 building-front
drwxr-xr-x  3 root     staff           512 Jan 1 1970 ne-sw-road
drwxr-xr-x  3 root     staff           512 Jan 1 1970 bear-hangout
drwxr-xr-x  3 root     staff           512 Jan 1 1970 se-nw-road
drwxr-xr-x  3 root     staff           512 Jan 1 1970 fork
drwxr-xr-x  3 root     staff           512 Jan 1 1970 e-w-dirt-road
drwxr-xr-x  3 root     staff           512 Jan 1 1970 dead-end
drwxr-xr-x  3 root     staff           512 Jan 1 1970 hidden-area
$ TECLEO: cd hidden-area

$ TECLEO: ls

total 4
drwxr-xr-x  3 root     staff           512 Jan 1 1970 .
drwxr-xr-x  3 root     staff          2048 Jan 1 1970 ..
-rwxr-xr-x  3 root     staff          2048 Jan 1 1970 description
-rwxr-xr-x  1 toukmond restricted        0 Jan 1 1970 bracelet.o
$ TECLEO: cat description

You are in a well-hidden area off to the side of a road.  Back to the
northeast through the brush you can see the bear hangout.
$ TECLEO: exit


You step back from the console.

>TECLEO: e

Old Building hallway
>TECLEO: s

Building front
>TECLEO: look

Building front
You are at the end of the road.  There is a building in front of you
to the northeast, and the road leads back to the southwest.
>TECLEO: sw

NE/SW road
>TECLEO: sw

Fork
>TECLEO: se

SE/NW road
>TECLEO: se

Bear hangout
>TECLEO: sw

Hidden area
There is an emerald bracelet here.
>TECLEO: take bracelet

Taken.  
>TECLEO: ne

Bear hangout
>TECLEO: nw

SE/NW road
>TECLEO: nw

Fork
>TECLEO: ne

NE/SW road
>TECLEO: ne

Building front
>TECLEO: in

Old Building hallway
>TECLEO: w

Computer room
The panel lights are flashing in a seemingly organized pattern.
>TECLEO: look

Computer room
You are in a computer room.  It seems like most of the equipment has
been removed.  There is a VAX 11/780 in front of you, however, with
one of the cabinets wide open.  A sign on the front of the machine
says: This VAX is named ‘pokey’.  To type on the console, use the
‘type’ command.  The exit is to the east.
The panel lights are flashing in a seemingly organized pattern.
>TECLEO: type

$ TECLEO: cd /usr/toukmond

$ TECLEO: ls

total 467
drwxr-xr-x  3 toukmond restricted      512 Jan 1 1970 .
drwxr-xr-x  3 root     staff          2048 Jan 1 1970 ..
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 ls
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 ftp
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 echo
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 exit
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 cd
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 pwd
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 rlogin
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 ssh
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 uncompress
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 cat
-rwxr-xr-x  1 toukmond restricted        0 Jan 1 1970 paper.o.Z
-rwxr-xr-x  1 toukmond restricted        0 Jan 1 1970 lamp.o
-rwxr-xr-x  1 toukmond restricted        0 Jan 1 1970 shovel.o
-rwxr-xr-x  1 toukmond restricted        0 Jan 1 1970 key.o
-rwxr-xr-x  1 toukmond restricted        0 Jan 1 1970 bracelet.o
$ TECLEO: uncompress paper.o.Z

$ TECLEO: exit


You step back from the console.

>TECLEO: inventory

You currently have:
A lamp
A shovel
A brass key
A bracelet
A slip of paper
>TECLEO: look paper

The paper says: Don't forget to type ‘help’ for help.  Also, remember
this word: ‘worms’
>TECLEO: type

$ TECLEO: ftp gamma

Connected to gamma. FTP ver 0.9 00:00:00 01/01/70
Username: TECLEO: anonymous
Guest login okay, send your user ident as password.
Password: 
TECLEO: toukmond@pockey
Guest login okay, user access restrictions apply.
ftp> 
TECLEO: help

Possible commands are:
send    quit    type   ascii  binary   help
ftp> TECLEO: type binary

Type set to binary.
ftp> TECLEO: send bracelet.o

Sending binary file for a bracelet, (0 bytes)
Transfer complete.
ftp> TECLEO: send paper.o

Sending binary file for a slip of paper, (0 bytes)
Transfer complete.
ftp> TECLEO: send shovel.o

Sending binary file for a shovel, (0 bytes)
Transfer complete.
ftp> TECLEO: send key.o

Sending binary file for a brass key, (0 bytes)
Transfer complete.
ftp> TECLEO: send lamp.o

Sending binary file for a lamp, (0 bytes)
Transfer complete.
ftp> TECLEO: quit

$ TECLEO: ls

total 467
drwxr-xr-x  3 toukmond restricted      512 Jan 1 1970 .
drwxr-xr-x  3 root     staff          2048 Jan 1 1970 ..
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 ls
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 ftp
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 echo
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 exit
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 cd
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 pwd
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 rlogin
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 ssh
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 uncompress
-rwxr-xr-x  1 toukmond restricted    10423 Jan 1 1970 cat
$ TECLEO: rlogin gamma

Password: TECLEO: worms

You begin to feel strange for a moment, and you lose your items.
You step back from the console.


Receiving room
You are in a round, stone room with a door to the east.  There
is a sign on the wall that reads: ‘receiving room’.
There is an emerald bracelet here.
There is a slip of paper here.
There is a shovel here.
There is a shiny brass key here.
There is a lamp nearby.
>TECLEO: take bracelet

Taken.  
>TECLEO: take paper

Taken.  
>TECLEO: take shovel

Taken.  
>TECLEO: take key

Taken.  
>TECLEO: take lamp

Taken.  
>TECLEO: look bracelet

I see nothing special about that.
>TECLEO: look lamp

The lamp is hand-crafted by Geppetto.
>TECLEO: look shovel

It is a normal shovel with a price tag attached that says $19.99.
>TECLEO: look key

I see nothing special about that.
>TECLEO: east

Northbound Hallway
You are at the south end of a hallway that leads to the north.  There
are rooms to the east and west.
>TECLEO: east

Sauna
You are in a sauna.  There is nothing in the room except for a dial
on the wall.  A door leads out to west.
It is normal room temperature in here.
>TECLEO: look dial

The dial points to a temperature scale which has long since faded away.
>TECLEO: turn dial counterclockwise

The dial will not turn further in that direction.
>TECLEO: look

Sauna
You are in a sauna.  There is nothing in the room except for a dial
on the wall.  A door leads out to west.
It is normal room temperature in here.
>TECLEO: turn dial counterclockwise

The dial will not turn further in that direction.
>TECLEO: look

Sauna
You are in a sauna.  There is nothing in the room except for a dial
on the wall.  A door leads out to west.
It is normal room temperature in here.
>TECLEO: turn dial counterclockwise

The dial will not turn further in that direction.
>TECLEO: look

Sauna
You are in a sauna.  There is nothing in the room except for a dial
on the wall.  A door leads out to west.
It is normal room temperature in here.
>TECLEO: west

Northbound Hallway
>TECLEO: north

End of N/S Hallway
You are at the end of a north/south hallway.  You can go back to the south,
or off to a room to the east.
>TECLEO: east

Weight room
You are in an old weight room.  All of the equipment is either destroyed
or completely broken.  There is a door out to the west, and there is a ladder
leading down a hole in the floor.
There is a 10 pound weight here.
There is a life preserver here.
>TECLEO: take weight

Your load would be too heavy.
>TECLEO: take life preserver

Taken.  
>TECLEO: look life preserver

It says S. S. Minnow.
>TECLEO: down

Maze button room
You are in a maze of twisty little passages, all alike.
There is a button on the ground here.
>TECLEO: look button

I see nothing special about that.
>TECLEO: press button

As you press the button, you notice a passageway open up, but
as you release it, the passageway closes.
>TECLEO:

>TECLEO: drop life preserver

Done.
>TECLEO: drop bracelet

Done.
>TECLEO: drop paper

Done.
>TECLEO: drop shovel

Done.
>TECLEO: drop key

Done.
>TECLEO: up

Weight room
There is a 10 pound weight here.
>TECLEO: take weight

Taken.  
>TECLEO: down

Maze button room
There is a life preserver here.
There is an emerald bracelet here.
There is a slip of paper here.
There is a shovel here.
There is a shiny brass key here.
>TECLEO: put weight on button

Done.
A passageway opens.
>TECLEO:

>TECLEO: nw

Maze
You are in a maze of little twisty passages, all alike.
>TECLEO: up

Maze
You are in a maze of thirsty little passages, all alike.
There is a wax statuette of Richard Stallman here.
There is a floppy disk here.
>TECLEO: take floppy

Taken.  
>TECLEO: take statuette

Taken.  
>TECLEO: look statuette

The statuette is of the likeness of Richard Stallman, the author of the
famous EMACS editor.  You notice that he is not wearing any shoes.
>TECLEO: # TENGO QUE VOLVER A LA SAUNA A FUNDIR LA STATUETTE

I don't understand that.
>TECLEO: s

Maze
>TECLEO: # ESTOY EN Maze little twisty passages

I don't understand that.
>TECLEO: look

Maze
You are in a maze of little twisty passages, all alike.
>TECLEO: up

Maze
>TECLEO: look

Maze
You are in a maze of thirsty little passages, all alike.
>TECLEO: # ESTOY EN Maze thirsty little passages, al south little twisty, al se twenty little

I don't understand that.
>TECLEO: se

Maze
You are in a maze of twenty little passages, all alike.
>TECLEO: look

Maze
You are in a maze of twenty little passages, all alike.
>TECLEO: # estoy en twenty little

I don't understand that.
>TECLEO: down

Maze
You are in a daze of twisty little passages, all alike.
>TECLEO: look

Maze
You are in a daze of twisty little passages, all alike.
>TECLEO: # estoy en daze of twisty little, twisty little cabbages al nw

I don't understand that.
>TECLEO: nw

Maze
You are in a maze of twisty little cabbages, all alike.
>TECLEO: look

Maze
You are in a maze of twisty little cabbages, all alike.
>TECLEO: # estoy en twisty little cabbages, reception area al nw

I don't understand that.
>TECLEO: ne

Weight room
>TECLEO: # vuelvo a Weight room

I don't understand that.
>TECLEO: w

End of N/S Hallway
>TECLEO: s

Northbound Hallway
>TECLEO: drop floppy

Done.
>TECLEO: e

Sauna
It is normal room temperature in here.
>TECLEO: # estoy en la sauna, a fundir la estatua

I don't understand that.
>TECLEO: drop statuette

Done.
>TECLEO: turn dial clockwise

It is now luke warm in here.  You are perspiring.
>TECLEO: turn dial clockwise

It is pretty hot in here.  It is still very comfortable.
>TECLEO: turn dial clockwise

It is now very hot.  There is something very refreshing about this.
You notice the wax on your statuette beginning to melt, until it completely
melts off.  You are left with a beautiful diamond!
>TECLEO: take diamond

Taken.  
>TECLEO: turn dial counterclockwise

It is pretty hot in here.  It is still very comfortable.
>TECLEO: turn dial counterclockwise

It is now luke warm in here.  You are perspiring.
>TECLEO: turn dial counterclockwise

The temperature has returned to normal room temperature.
>TECLEO: turn dial counterclockwise

The dial will not turn further in that direction.
>TECLEO: w

Northbound Hallway
There is a floppy disk here.
>TECLEO: take floppy

Taken.  
>TECLEO: look

Northbound Hallway
You are at the south end of a hallway that leads to the north.  There
are rooms to the east and west.
>TECLEO: quit


You have scored 0 out of a possible 90 points.
:END:

** otro apartado
   adsadfs
